# Worker project name (never .js)
name = "ultracipher_releases"

# Entry file â€” your Worker code
main = "UltraDownloader.js"

# Cloudflare compatibility date
compatibility_date = "2026-01-28"

# KV namespace binding (if needed)
[[kv_namespaces]]
binding = "ULTRACIPHER_SETUP"
id = "94e1ba72-662d-4e55-abbb-dc6db7e6e21f"

# Workers_dev = false if deploying to custom subdomain
workers_dev = true

# Optional: restrict HTTP methods
[triggers]
allowed_methods = ["GET"]
