name = "ultracipher"
main = "ultracipher_setup.js"
compatibility_date = "2026-01-30"


# Workers_dev = false if deploying to custom subdomain
workers_dev = false

# Optional: restrict HTTP methods
[triggers]
allowed_methods = ["GET"]
